<div id="divContent">
  <form action="enter-wrk.php" method="post">
    <input type="text" name="name" id="name" placeholder="<?=trans('Name')?>" /><br />
    <input type="password" name="pass" id="pass" placeholder="<?=trans('Pass')?>" /><br />
    <input type="submit" value="<?=trans('Enter')?>" />
  </form>
</div>
<link href="enter-vue.css" rel="stylesheet" />
<script src="enter-vue.js"></script>
